### ISSUE TITLE
Have you evaluated the performance of the 3B model?

### ISSUE THREAD

**Issue by heya5** [jozhang97/ism#1]
Hi, I am curious about the performance of your method on ESM-3B, but I did not see it mentioned in your paper or repo.

**Comment by jozhang97** [comment]
We conducted a brief evaluation of our ESM-2 model with 3B parameters and found that its performance was comparable to the 650M version.
Unless there's a specific reason you need to use the 3B model, we recommend defaulting to the 650M model.

**Comment by heya5** [comment]
@jozhang97  hi, what about the performance of you latest released model based in esmc 600M or 300M?

**Comment by jozhang97** [comment]
Hi,

Thanks for your interest.
We did not find substantial difference in performance. Here are the results on the contact prediction benchmark.

| Method | Params | S    | M    | L    |
|--------|--------|------|------|------|
| ESM2   |  650M  | 0.56 | 0.53 | 0.38 |
| ESM-C  |  600M  | 0.56 | 0.56 | 0.41 |
| ISM-C  |  600M  | 0.62 |  0.6 | 0.47 |
| ISM    | 650M   | 0.62 | 0.59 | 0.49 |

**Comment by heya5** [comment]
Thanks for the reply!
